### ISSUE TITLE
Disable the cheat protection

### ISSUE THREAD

**Issue by Leseratte10** [Chadderz121/wii-ct-code#5]
Is there any way to disable the cheat protection of the ct-code?

Whenever I try to load MKWii with ct-code and enabled Ocarina or WiiRD, I only get a black screen ...

**Comment by Chadderz121** [comment]
The published version here should have no cheat protection. If you borrowed a .dol file from CTGP-R v1.02 or similar, you may have inherited the protection from that.

**Comment by kyle95wm** [comment]
A direct copy/paste from YouTube:

This tutorial will show you how to remove the cheat security from CTGPR

I would like to give thanks to Chadderz for helping me with this


If you are NTSCU:
1) open the main.dol in your favourite hex editor
2) go to offset 0x84 making sure to replace 80 00 28 00 with 80 2A 80 00
3) go to 0x29F354 and do what you did in step 2 by making sure to replace 80 00 28 00 with 80 2A 80 00

Save and enjoy

For PAL users:

1) open the main.dol in your favourite hex editor
2) go to offset 0x84 making sure to replace 80 00 28 00 with 80 2A 80 00
3) go to 0x2A36B4 and do what you did in step 2 by making sure to replace 80 00 28 00 with 80 2A 80 00

Save and enjoy

For NTSCJ users:
1) open the main.dol in your favourite hex editor
2) go to offset 0x84 making sure to replace 80 00 28 00 with 80 2A 80 00
3) go to 0x2A3034 and do what you did in step 2 by making sure to replace 80 00 28 00 with 80 2A 80 00

Save and enjoy


The rough documentation

NTSCJ 0x84 and 0x2A3034
NTSCU 0x84 and 0x29F354
PAL 0x84 and 0x2A36B4
search 80 00 28 00 00 00 00 00 00 00 00 00 in hex editor
Replace with 80 2A 80 00
