### ISSUE TITLE
Please support NTSCK

### ISSUE THREAD

**Issue by Aiden9999VR** [Chadderz121/wii-ct-code#7]
I wish support NTSCK version.(CTGPR) I want to play CTGPR..Please...if you need RMCK, download in this link: `<deleted link>`

its on google drive, it hasn't virus. really. my first wish is play CTGPR. Please support NTSCK. I belive Chadderz can make NTSCK support. Bye!

**Comment by Chadderz121** [comment]
Duplicate of #4
